### ISSUE TITLE
Supported Arduino Boards?

### ISSUE THREAD

**Issue by Espionage724** [mon/Arduino-HID-Lighting#1]
Does this project happen to "just work" with any specific board(s)?

I'm specifically thinking about [this with a ATmega328P](https://www.ebay.com/itm/MINI-USB-Nano-V3-0-ATmega328P-CH340G-5V-16M-Micro-controller-board-Arduino/222543127037)

**Comment by mon** [comment]
It will only work with arduino boards (or clones) that have a USB component - that's anything with an Atmega32u4.

I'd recommend [something like this](https://www.ebay.com/itm/New-Pro-Micro-ATmega32U4-5V-16MHz-Replace-ATmega328-Arduino-Pro-Mini-new/261809188156), it's about the same cost. If that link ever dies, "Leonardo pro micro" is a good search term to find that board.
