### ISSUE TITLE
Modify Sketch

### ISSUE THREAD

**Issue by jskima** [mon/Arduino-HID-Lighting#4]
Sorry. I'm a beginner.
Is there any code to modify to use the Neo pixel?
Or, to use normal RGBLEDs
Do I need to modify this code?
If you possible, please tell me how to modify the sketch file.
I use Adafruit_NeoPixel library

And it still does not work with the bemani tool version 4.25 (JubeatQubell). ><

**Comment by mon** [comment]
Try bemanitools 5 - it appears to have working lights.

You should reference the adafruit documentation for the neopixels. I may be able to write an example though

**Comment by jskima** [comment]
Does Bemanitools 5 version exist?
As far as I know, 4.25 is the latest.

**Comment by jskima** [comment]
// ******************************
// EDIT THESE LINES

// The single LEDs will be first in BTools
// The RGB LEDs will come afterwards, with R/G/B individually
#define NUMBER_OF_SINGLE 0
#define NUMBER_OF_RGB 1

/* Important note!
 *  NEOPIXELS:
 *  You cannot use strip.show() inside light_update, since it is inside
 *  an interrupt handler. Instead, make a variable eg:
 *   volatile bool needs_update = false;
 *  When you want to show your lights, set it to true. (eg inside light_update)
 *  Then, inside loop():
 *   if(needs_update) {
 *     strip.show();
 *     needs_update = false;
 *   }
 */

void light_update(SingleLED* single_leds, RGBLed* rgb_leds) {
  for(int i = 0; i < NUMBER_OF_SINGLE; i++) {
    // YOUR CODE HERE
    // led_stuff(single_leds[i].brightness);
  }
  for(int i = 0; i < NUMBER_OF_RGB; i++) {
    // YOUR CODE HERE
    // rgb_stuff(rgb_leds[i].r, rgb_leds[i].g, rgb_leds[i].b);
  }
}

void setup() {
  // setup your LEDs here
}

void loop() {
  // USB module does the hard work
}

// ******************************
// don't need to edit below here


I don't understand how it modify this lines.
All I want to know is How to write the PIN OUT code.

**Comment by jskima** [comment]
Thanks for your kind and Thank you for answering my poor English.
