### ISSUE TITLE
Inquiry and Request

### ISSUE THREAD

**Issue by JerryDaga** [mon/Arduino-HID-Lighting#7]
Request a new Code for Arduino Leonardo, Etc.
for Drummania, Gitadora, or E-Drums (for Music Studio Application) using Piezoelectric...
because is too hard to find a code and I want to play Drummania too.

Please... 🙏🙏🙏🙏🙏🙏

**Comment by mon** [comment]
Sorry, but that is actually a little hard and I don't have time for it. You may have luck asking people in the Cons&Stuff discord.
